name: build-workflow

on:
  push:
    tags:
      - "*"
    branches:
      - ci-build-workflow

  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
      - uses: taiki-e/install-action@just
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: '~> v1'
          install-only: true
      - run: just build
      - uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: "*.zip"

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: |
      always() &&
      startsWith(github.ref, 'refs/tags/') &&
      needs.build.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: true
